# fly.toml app configuration file generated for omoprag-api on 2025-05-15T06:33:09+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'omoprag-api'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[env]
  CHROMA_PATH = '/data/chroma_db'
  COLLECTION_NAME = 'omop_concepts_openai'
  PORT = '8080'

[mounts]
  source = 'omoprag_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 500

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
